from .nn.training_utils import apply_updates
from .nn.training_utils import eval_mode
from .nn.training_utils import BackwardRecorder
from .nn import optimizers
from .backend import platform
from .backend import devices
from .backend import is_gpu_available
from .backend import device_count
from .backend import track_tensor
from .backend import create_keys
from .backend import save_weights
from .backend import load_weights
from .backend import set_global_rng